
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module bubble4(
	/*
	//////////// CLOCK //////////
	input 		          		ADC_CLK_10,
	input 		          		MAX10_CLK1_50,
	input 		          		MAX10_CLK2_50,

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW */
	
input [3:0] bubin3,
input [3:0] bubin2,
input [3:0] bubin1,
input [3:0] bubin0,
output [3:0] bubout3,
output [3:0] bubout2,
output [3:0] bubout1,
output [3:0] bubout0
	
);
wire [3:0] btw2;
wire [3:0] btw1;
	

//=======================================================
//  REG/WIRE declarations
//=======================================================


//=======================================================
//  Structural coding
//=======================================================

lab3sortp1 lab3sortp1_1(.in1(bubin3), .in0(bubin2), .out1(bubout3), .out0(btw2));

lab3sortp1 lab3sortp1_2(.in1(btw2), .in0(bubin1), .out1(bubout2), .out0(btw1));
lab3sortp1 lab3sortp1_3(.in1(btw1), .in0(bubin0), .out1(bubout1), .out0(bubout0));

endmodule
