
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module sort4(

	//////////// CLOCK //////////
	//input 		          		ADC_CLK_10,
	//input 		          		MAX10_CLK1_50,
	//input 		          		MAX10_CLK2_50,

	//////////// SEG7 //////////
	//output		     [7:0]		HEX0,
	//output		     [7:0]		HEX1,
	//output		     [7:0]		HEX2,
	//output		     [7:0]		HEX3,
	//output		     [7:0]		HEX4,
	//output		     [7:0]		HEX5,

	//////////// KEY //////////
	//input 		     [1:0]		KEY,

	//////////// LED //////////
	//output		     [9:0]		LEDR,

	//////////// SW //////////
	//input 		     [1:0]		SW
input [3:0] ins4_3,
input [3:0] ins4_2,
input [3:0] ins4_1,
input [3:0] ins4_0,

output  [3:0] outs4_3,
output  [3:0] outs4_2,
output  [3:0] outs4_1,
output  [3:0] outs4_0
	
);

//=======================================================
//  REG/WIRE declarations
//=======================================================

wire [3:0] a3;
wire [3:0] a2;
wire [3:0] a1;
wire [3:0] a0;
wire [3:0] b3;
wire [3:0] b2;
wire [3:0] b1;
wire [3:0] b0;







//=======================================================
//  Structural coding
//=======================================================


bubble4 bubble4_1(.bubin3(ins4_3), .bubin2(ins4_2), .bubin1(ins4_1), .bubin0(ins4_0), .bubout3(a3), .bubout2(a2), .bubout1(a1), .bubout0(a0));

bubble4 bubble4_2(.bubin3(a3), .bubin2(a2), .bubin1(a1), .bubin0(a0), .bubout3(b3), .bubout2(b2), .bubout1(b1), .bubout0(b0));

bubble4 bubble4_3(.bubin3(b3), .bubin2(b2), .bubin1(b1), .bubin0(b0), .bubout3(outs4_3), .bubout2(outs4_2), .bubout1(outs4_1), .bubout0(outs4_0));




endmodule
